[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "microvenv"
version = "2023.2.0"
description = "A minimal re-implementation of Python's venv module"
keywords = ["virtual environments", "venv"]
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [{ name = "Brett Cannon", email = "brett@python.org" }]
authors = [{ name = "Brett Cannon", email = "brett@python.org" }]
requires-python = ">=3.7"
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "Topic :: Utilities",
  "Natural Language :: English",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX",
]

[project.optional-dependencies]
test = ["pytest"]
lint = ["black", "mypy", "ruff"]

[project.urls]
Changelog = "https://github.com/brettcannon/microvenv/releases"
Source = "https://github.com/brettcannon/microvenv"


[tool.mypy]
ignore_missing_imports = true
