name: "CI"

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macOS"]

    steps:
      - uses: actions/checkout@v3
      - name: "Setup Python & Nox"
        uses: daisylb/setup-nox@v2
      - run: nox
